#!/usr/bin/env node
"use strict";

var fs = require('fs');
var WebSocket = require('ws');
var path = require('path');
const assert = require('assert');
const Common = require('./../../../lib/jibo-platform-test/common');
var hostname = "localhost";

const paths = ['/wifi/messages', '/system_notifications'];

describe('System Manager WS Tests', function() {

    for(let i = 0; i < paths.length; i++) {
	    it('Testing the ' + paths[i].substring(1) + ' API', function() {
	        Common._testJSON(hostname, ":8585", paths[i], (err) => {
		    assert(!err, 'Error parsing JSON for ' + paths[i] + ': ' + err.message);
	        })
	    });
    }
    after(function() {
        console.log("- Finished testing the system manager WS APIs")
    });
});

