# -*- mode:text; coding:utf-8 -*-
Analyzing at 1.960938,21.007813
------------------ FRs -----------------

15% FR: CONTINUE [542 / (1172*3)]
	-> CONTINUE (535 = 98.71%)
	-> PAUSE (7 = 1.29%)

25% FR: PAUSE [785 / (1032*3)]
	-> CONTINUE (239 = 30.45%)
	-> PAUSE (546 = 69.55%)

------------------ FAs -----------------
0.44 FAs/hr: CONTINUE [4 / 9.19]
1.52 FAs/hr: PAUSE [14 / 9.19]

